### ISSUE TITLE
Ошибки с кодировкой для MySQL

### ISSUE THREAD

**Issue by casada-russia** [OWOX/BigQuery-integrations#1]
При попытке запуска функции для MySQL в BigQuery кириллические символы отображаются как знаки вопроса. 

Кодировка в исходной базе utf8_general_ci

![image](https://user-images.githubusercontent.com/50951362/65886726-84e1a480-e3a5-11e9-801d-f2cac15b98a6.png)

**Comment by casada-russia** [comment]
Решилось если прописать
`cursor = cnx.cursor(raw=True)` 
вместо
`cursor = cnx.cursor()`

**Comment by s-krava** [comment]
@casada-russia спасибо за комментарий.
Обратите внимание, что `cursor = cnx.cursor(raw=True)` [пропускает](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursorraw.html) конвертацию типов объектов с MySQL -> Python. Тут могут возникнуть проблемы, когда скрипт будет загружать файл в BigQuery. Так как мы не прописываем схему, а используем автоопределение схемы, то могут появится неожиданные результаты.

Если что то будет работать неожиданно, можно попробовать:

1. Оставить `cursor = cnx.cursor()`
2. Добавить параметр **charset** с указанием кодировки в функцию connect:
```
     cnx = connect(user = mysql_configuration["user"], 
                             passwd = mysql_configuration["psswd"], 
                             host = mysql_configuration["host"],
                             db = mysql_configuration["database"], 
                             port = mysql_configuration["port"],
                             cursorclass= cursors.DictCursor,
                             charset = "utf8")

```
