### ISSUE TITLE
Не выгружаются контакты

### ISSUE THREAD

**Issue by ikulakov** [OWOX/BigQuery-integrations#3]
Версия скрипта от 13.12, все таблицы выгружаются корректно, при выгрузке таблицы Contact, получаю следующие ошибки:

> 400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 546; errors: 1. Please look into the errors[] collection for more details.

> JSON parsing error in row starting at position 345655: JSON object specified for non-record field: company

С чем может быть связано?

**Comment by vikingUnet** [comment]
Возможно мой pull request решит проблему, скорее всего. Пока его не добрили - возьми файл в моём форке репозитория

**Comment by ikulakov** [comment]
> Возможно мой pull request решит проблему, скорее всего. Пока его не одобрили - возьми файл в моём форке репозитория

Спасибо. Его и пользую, тот что залит родной вообще ни одну таблицу нормально не выгружает.

**Comment by vikingUnet** [comment]
Проблема в поле company внутри таблицы contacts - то ли это поле присутствует не у всех строк (тогда нужно добавить пустое значение в каждую строку, где нет этого поля), то ли у некоторых строк в этом поле есть реальные значения определенной структуры (тогда нужно поддержать эту структуры даже для каждого пустого или отсутствующего значения поля company). В общем две гипотезы - нужно перебирать значения внутри функции загрузки данных в BQ по строкам и проверять на ваших данных

**Comment by ikulakov** [comment]
Видимо проблема все-таки в том что поле company присутствовало не у всех строк, и нужно заполнять пустым значением его. Удалил компании у контактов за ненадобностью, проблема ушла. Но следом получил такую-же с тегами

> JSON parsing error in row starting at position 489386: Array specified for non-repeated field: tags.

**Comment by vikingUnet** [comment]
Я посмотрел описание api https://www.amocrm.ru/developers/content/api/contacts для сущности контакты и добавил в код поведение чтобы всегда создавать отсутствующие ключи для полей типа array - это поля "company", "leads", "tags", "custom_fields", "customers". Строки 81 - 83 в моём форке, можешь попробовать с этими правками.

**Comment by ikulakov** [comment]
Проблему с "company" новый код решил, проблема с тегами к сожалению осталась

> JSON parsing error in row starting at position 489386: Array specified for non-repeated field: tags.

**Comment by vikingUnet** [comment]
Из того, что я нашёл - в массивах могут быть списки однотипных элементов и чтобы это заработало, нужно задать режим повторения - mode = repeated. Добавил в 20 строку режим настройки объекта клиента BigQuery - "job_config.flatten_results = True". Попробуй с этой правкой, очень надеюсь, что решит проблему.

**Comment by ikulakov** [comment]
Не помогло(

**Comment by s-krava** [comment]
@ikulakov Привет.
Проблема в том, что автоопределение схемы не срабатывает корректно из-за пропусков в полях. Попробуй отказаться от автоопределения схемы BigQuery и прописать ее в ручную. Тебе нужно:

1. Найти в функции `load_to_gbq` строку `job_config.autodetect = True` и удалить ее.
2. Вместо нее нужно определить схему таблицы **job_config.schema** .

Например, для файла в такой структуре
` {'field_1': 'value_1', 'field_2': {'field_3': 'value_3'}}` **job_config.schema** нужно задать так:

```
    job_config.schema = [
        bigquery.SchemaField('field_1', 'STRING', mode = 'NULALBLE'),
        bigquery.SchemaField('field_2', field_type = "RECORD", mode = "REPEATED", fields = [
            bigquery.SchemaField(name = "field_3", field_type="STRING", mode = "NULLABLE")]
    ]
```
Нужно четко определить схему и учесть все вложенности и возможные поля. 

Проблема может остаться, если файл будет в не подходящей для BigQuery [структуре](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json#loading_nested_and_repeated_json_data). Но без файла тяжело сказать.
